project:
  type: website
  output-dir: docs

website:
  title: "Rodrigo Veiga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - fp-research-design.qmd
      - fp-research-design-expanded.qmd
      - final-submission.qmd
  page-footer: 
    right: |
        Made with R and [Quarto](https://quarto.org/)<br>
        [View the source at {{< fa brands github >}} GitHub](https://github.com/rveigac/scm-application-rodrigo-veiga)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



