project:
  type: website
  output-dir: docs

website:
  title: "scm-application-rodrigo-veiga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - 3200-fp-research-design.qmd
      - 3200-fp-research-design-expanded.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



